# Generated by Django 2.1.7 on 2019-03-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(max_length=50)),
                ('picture', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=140)),
                ('flavor1', models.CharField(max_length=10)),
                ('flavor2', models.CharField(max_length=10)),
                ('flavor3', models.CharField(max_length=10)),
                ('flavor4', models.CharField(max_length=10)),
            ],
        ),
    ]
