# Generated by Django 2.1.7 on 2019-03-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='coffee_pics'),
        ),
    ]
