# Generated by Django 2.1.7 on 2019-03-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_remove_orders_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=20)),
                ('flavor_choice', models.CharField(max_length=10)),
                ('customize', models.CharField(max_length=140)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=10)),
            ],
        ),
    ]
