# Generated by Django 2.1.7 on 2019-03-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_drinkchoice_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkchoice',
            name='choice',
            field=models.CharField(max_length=50),
        ),
    ]
